hi

diff --git a/.github/workflows/realease_package.yml b/.github/workflows/realease_package.yml
--- a/.github/workflows/realease_package.yml
+++ b/.github/workflows/realease_package.yml
@@ -34,12 +34,26 @@ jobs:
       - name: List directory contents
         run: ls -la dist/
         shell: bash
-      - name: Get OIDC token1
+      - name: Get OIDC Token from GitHub and Exchange with Cloudsmith
         run: |
-          value=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq '.value')
-          token=$(curl -X POST -H "Content-Type: application/json" -d "{\"oidc_token\":$value, \"service_slug\":\"$CLOUDSMITH_SERVICE_SLUG\"}" https://api.cloudsmith.io/openid/$CLOUDSMITH_NAMESPACE/ | jq -r '.token')
-          curl --request GET --url https://api.cloudsmith.io/v1/user/self/ --header "X-Api-Key:Bearer $token" --header 'accept: application/json'
-          echo "CLOUDSMITH_API_KEY=$token" >> $GITHUB_ENV
+          echo "🔐 Requesting OIDC token from GitHub..."
+
+          oidc_token=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
+            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=https://github.com/rini-jain" | jq -r '.value')
+
+          echo "🔁 Exchanging token with Cloudsmith..."
+          cloudsmith_token=$(curl -s -X POST -H "Content-Type: application/json" \
+            -d "{\"oidc_token\":\"$oidc_token\", \"service_slug\":\"${{ env.CLOUDSMITH_SERVICE_SLUG }}\"}" \
+            "https://api.cloudsmith.io/openid/${{ env.CLOUDSMITH_NAMESPACE }}/" | jq -r '.token')
+
+          if [ -n "$cloudsmith_token" ]; then
+            echo "CLOUDSMITH_API_KEY=$cloudsmith_token" >> $GITHUB_ENV
+            echo "✅ Token exchange succeeded"
+          else
+            echo "❌ Token exchange failed"
+            exit 1
+          fi
+
       - name: Debug OIDC Token
         run: |
             echo "ACTIONS_ID_TOKEN_REQUEST_URL: $ACTIONS_ID_TOKEN_REQUEST_URL"
